// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNPhsZi5DnY_sMh_qkIILNueEhj5U1Lss',
    appId: '1:890320144828:web:3e01553f5c3a8a2721c3b9',
    messagingSenderId: '890320144828',
    projectId: 'programsiramtanamotomatis',
    authDomain: 'programsiramtanamotomatis.firebaseapp.com',
    databaseURL: 'https://programsiramtanamotomatis-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programsiramtanamotomatis.appspot.com',
    measurementId: 'G-FKZDJ4KYZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkwMxhtEFgL-04ccDmnsuFTo5As-93gSM',
    appId: '1:890320144828:android:fa85bf0251d8a85d21c3b9',
    messagingSenderId: '890320144828',
    projectId: 'programsiramtanamotomatis',
    databaseURL: 'https://programsiramtanamotomatis-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programsiramtanamotomatis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9qD9AkVrSBtTIIdm10Lf4YNScmmWf39k',
    appId: '1:890320144828:ios:35df6ea5b36b902021c3b9',
    messagingSenderId: '890320144828',
    projectId: 'programsiramtanamotomatis',
    databaseURL: 'https://programsiramtanamotomatis-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programsiramtanamotomatis.appspot.com',
    iosBundleId: 'com.example.sitanamalvian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9qD9AkVrSBtTIIdm10Lf4YNScmmWf39k',
    appId: '1:890320144828:ios:35df6ea5b36b902021c3b9',
    messagingSenderId: '890320144828',
    projectId: 'programsiramtanamotomatis',
    databaseURL: 'https://programsiramtanamotomatis-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programsiramtanamotomatis.appspot.com',
    iosBundleId: 'com.example.sitanamalvian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNPhsZi5DnY_sMh_qkIILNueEhj5U1Lss',
    appId: '1:890320144828:web:722aec7da4b8646921c3b9',
    messagingSenderId: '890320144828',
    projectId: 'programsiramtanamotomatis',
    authDomain: 'programsiramtanamotomatis.firebaseapp.com',
    databaseURL: 'https://programsiramtanamotomatis-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programsiramtanamotomatis.appspot.com',
    measurementId: 'G-BQBKF582GT',
  );
}
